// 12人のキャラクターロスター定義
// stats: hp(体力), speed(移動速度倍率), power(攻撃力倍率), reach(リーチ倍率)
// body: height/bulk は体格スケール
// special.anim は fighter.js の特殊技アニメ種別に対応

export const CHARACTERS = [
  {
    id: 'ryuji',
    name: 'RYUJI',
    nameJa: '隆司',
    style: '空手',
    country: '日本',
    colors: { gi: 0xeeeeee, gi2: 0x222222, skin: 0xd9a47e, hair: 0x1a1a1a },
    body: { height: 1.0, bulk: 1.0 },
    stats: { hp: 100, speed: 1.0, power: 1.0, reach: 1.0 },
    accessory: 'headband',
    accessoryColor: 0xcc2222,
    special: { name: '轟雷正拳', anim: 'lungePunch', damage: 22, desc: '踏み込み正拳突き' },
  },
  {
    id: 'meilin',
    name: 'MEI-LIN',
    nameJa: '美鈴',
    style: '八極拳',
    country: '中国',
    colors: { gi: 0xc0392b, gi2: 0xf1c40f, skin: 0xe8b88a, hair: 0x140f0a },
    body: { height: 0.93, bulk: 0.85 },
    stats: { hp: 90, speed: 1.2, power: 0.9, reach: 0.92 },
    accessory: 'bun',
    accessoryColor: 0x140f0a,
    special: { name: '崩山靠', anim: 'shoulderBash', damage: 20, desc: '鉄山靠の如き体当たり' },
  },
  {
    id: 'viktor',
    name: 'VIKTOR',
    nameJa: 'ヴィクトル',
    style: 'コマンドサンボ',
    country: 'ロシア',
    colors: { gi: 0x2c3e50, gi2: 0xbdc3c7, skin: 0xe6c3a5, hair: 0xd4c08a },
    body: { height: 1.12, bulk: 1.35 },
    stats: { hp: 125, speed: 0.75, power: 1.3, reach: 1.05 },
    accessory: 'beard',
    accessoryColor: 0xb09a60,
    special: { name: 'シベリアンハンマー', anim: 'overheadSmash', damage: 28, desc: '両腕の振り下ろし' },
  },
  {
    id: 'sofia',
    name: 'SOFIA',
    nameJa: 'ソフィア',
    style: 'カポエイラ',
    country: 'ブラジル',
    colors: { gi: 0x27ae60, gi2: 0xf9e547, skin: 0x9c6b43, hair: 0x2b1b10 },
    body: { height: 0.97, bulk: 0.9 },
    stats: { hp: 92, speed: 1.18, power: 0.95, reach: 1.02 },
    accessory: 'longhair',
    accessoryColor: 0x2b1b10,
    special: { name: 'メイア・ルーア', anim: 'spinKick', damage: 21, desc: '回転大車輪蹴り' },
  },
  {
    id: 'marcus',
    name: 'MARCUS',
    nameJa: 'マーカス',
    style: 'ボクシング',
    country: 'アメリカ',
    colors: { gi: 0x2980b9, gi2: 0xe74c3c, skin: 0x7a4a26, hair: 0x0d0d0d },
    body: { height: 1.05, bulk: 1.15 },
    stats: { hp: 110, speed: 1.0, power: 1.15, reach: 0.95 },
    accessory: 'cap',
    accessoryColor: 0xe74c3c,
    special: { name: 'メガトンスマッシュ', anim: 'lungePunch', damage: 25, desc: '渾身のダッシュストレート' },
  },
  {
    id: 'kazane',
    name: 'KAZANE',
    nameJa: '風音',
    style: '忍術',
    country: '日本',
    colors: { gi: 0x34203b, gi2: 0x9b59b6, skin: 0xe8c39e, hair: 0x3d2b56 },
    body: { height: 0.92, bulk: 0.8 },
    stats: { hp: 82, speed: 1.35, power: 0.85, reach: 0.95 },
    accessory: 'mask',
    accessoryColor: 0x9b59b6,
    special: { name: '疾風斬', anim: 'dashStrike', damage: 18, desc: '神速の突進斬' },
  },
  {
    id: 'diego',
    name: 'DIEGO',
    nameJa: 'ディエゴ',
    style: 'ルチャリブレ',
    country: 'メキシコ',
    colors: { gi: 0xf39c12, gi2: 0x16a085, skin: 0xc68a52, hair: 0x16a085 },
    body: { height: 1.0, bulk: 1.2 },
    stats: { hp: 112, speed: 0.95, power: 1.18, reach: 0.98 },
    accessory: 'luchamask',
    accessoryColor: 0x16a085,
    special: { name: 'フライングクロスチョップ', anim: 'flyingStrike', damage: 24, desc: '跳躍チョップ' },
  },
  {
    id: 'anong',
    name: 'ANONG',
    nameJa: 'アノン',
    style: 'ムエタイ',
    country: 'タイ',
    colors: { gi: 0x8e44ad, gi2: 0xf1c40f, skin: 0xb5793f, hair: 0x111111 },
    body: { height: 1.0, bulk: 0.98 },
    stats: { hp: 100, speed: 1.05, power: 1.08, reach: 1.0 },
    accessory: 'headband',
    accessoryColor: 0xf1c40f,
    special: { name: '飛膝蹴り', anim: 'flyingStrike', damage: 23, desc: 'カオローイ（飛び膝）' },
  },
  {
    id: 'yuna',
    name: 'YUNA',
    nameJa: 'ユナ',
    style: 'テコンドー',
    country: '韓国',
    colors: { gi: 0xecf0f1, gi2: 0x3498db, skin: 0xeec9a6, hair: 0x241a14 },
    body: { height: 0.96, bulk: 0.88 },
    stats: { hp: 90, speed: 1.15, power: 0.95, reach: 1.1 },
    accessory: 'ponytail',
    accessoryColor: 0x241a14,
    special: { name: '旋風三連脚', anim: 'spinKick', damage: 22, desc: '回転三連蹴り' },
  },
  {
    id: 'rajan',
    name: 'RAJAN',
    nameJa: 'ラジャン',
    style: 'カラリパヤット',
    country: 'インド',
    colors: { gi: 0xd35400, gi2: 0xecf0f1, skin: 0x8d5a2b, hair: 0x0a0a0a },
    body: { height: 1.06, bulk: 0.92 },
    stats: { hp: 96, speed: 1.0, power: 1.0, reach: 1.18 },
    accessory: 'topknot',
    accessoryColor: 0x0a0a0a,
    special: { name: 'ヴァジュラ突き', anim: 'dashStrike', damage: 21, desc: '雷霆の貫手' },
  },
  {
    id: 'owen',
    name: 'OWEN',
    nameJa: 'オーウェン',
    style: '総合格闘技',
    country: 'イギリス',
    colors: { gi: 0x1e272e, gi2: 0xd63031, skin: 0xe9bf9b, hair: 0x6d4c2f },
    body: { height: 1.03, bulk: 1.08 },
    stats: { hp: 105, speed: 1.0, power: 1.1, reach: 1.0 },
    accessory: 'mohawk',
    accessoryColor: 0x6d4c2f,
    special: { name: 'スーパーマンパンチ', anim: 'flyingStrike', damage: 24, desc: '跳び込み拳' },
  },
  {
    id: 'zara',
    name: 'ZARA',
    nameJa: 'ザラ',
    style: 'サバット',
    country: 'フランス',
    colors: { gi: 0x130f40, gi2: 0xe056fd, skin: 0x5e3a1e, hair: 0x0c0c0c },
    body: { height: 0.99, bulk: 0.86 },
    stats: { hp: 88, speed: 1.22, power: 0.92, reach: 1.05 },
    accessory: 'shorthair',
    accessoryColor: 0x0c0c0c,
    special: { name: 'フェッテ・トルネード', anim: 'spinKick', damage: 21, desc: '竜巻回し蹴り' },
  },
];
